
import { ServiceProvider } from './types';

const MOCK_REVIEWS = [
  { id: 'r1', user: 'Aditi V.', rating: 5, comment: 'Excellent service! Very polite and professional.', date: 'Today' },
  { id: 'r2', user: 'Rahul K.', rating: 4, comment: 'Highly skilled. Fixed the issue which 3 others couldn\'t.', date: '3 days ago' },
  { id: 'r3', user: 'Sanjana M.', rating: 5, comment: 'Punctual and uses quality genuine spare parts.', date: '2 weeks ago' }
];

export const SERVICE_PROVIDERS: ServiceProvider[] = [
  {
    id: '1',
    name: 'Arjun Mehta',
    category: 'Plumbing',
    location: 'Koramangala, Bangalore',
    availability: 'Available',
    rating: 4.9,
    reviewsCount: 342,
    reviews: MOCK_REVIEWS,
    price: '₹499',
    avatar: 'images/plumber.webp',
    lat: 12.9352,
    lng: 77.6245,
    description: 'Specialist in high-pressure bathroom fittings and leakage solutions.',
    longBio: 'With 12 years of experience working with top real estate firms in Bangalore, I provide premium plumbing solutions ranging from Jaquar fittings to complex drainage mapping.',
    skills: ['Hydro-jetting', 'Bathroom Fittings', 'Solar Water Heaters'],
    yearsExperience: 12,
    responseTime: '15 mins',
    verified: true,
    repeatCustomers: 124,
    certifications: ['Master Plumber Assoc.', 'Water Safety Cert'],
    equipment: ['High-Pressure Jetter', 'Thermal Leak Detector', 'Electric Pipe Threader'],
    completedJobs: 1450
  },
  {
    id: '2',
    name: 'Priya Sharma',
    category: 'Beauty',
    location: 'Indiranagar, Bangalore',
    availability: 'Busy',
    rating: 5.0,
    reviewsCount: 189,
    reviews: MOCK_REVIEWS,
    price: '₹1200',
    avatar: 'images/makeup.jpg',
    lat: 12.9784,
    lng: 77.6408,
    description: 'Certified bridal makeup artist and premium skin therapist.',
    longBio: 'Trained at top academies in Mumbai, I bring salon-grade luxury to your home. Expert in HD makeup and organic facials.',
    skills: ['Bridal Makeup', 'O3+ Facials', 'Aromatherapy'],
    yearsExperience: 8,
    responseTime: '30 mins',
    verified: true,
    repeatCustomers: 95,
    certifications: ['MAC Pro Artist', 'Skin Esthetician Diploma'],
    equipment: ['Professional LED Kit', 'Hypoallergenic Makeup', 'Steamers'],
    completedJobs: 820
  },
  {
    id: '3',
    name: 'Rajesh Iyer',
    category: 'Electrical',
    location: 'HSR Layout, Bangalore',
    availability: 'Available',
    rating: 4.8,
    reviewsCount: 256,
    reviews: MOCK_REVIEWS,
    price: '₹350',
    avatar: 'images/electrician.jpg',
    lat: 12.9141,
    lng: 77.6411,
    description: 'Master electrician specializing in UPS/Inverter setups and LED lighting.',
    longBio: 'I specialize in home automation and power backup solutions. I ensure your home is safe from voltage fluctuations with certified earthing solutions.',
    skills: ['Inverter Setup', 'Home Automation', 'Main Line Repair'],
    yearsExperience: 15,
    responseTime: '20 mins',
    verified: true,
    repeatCustomers: 210,
    certifications: ['Grade A Wireman', 'Solar Grid Specialist'],
    equipment: ['Digital Multimeter', 'Insulated Tool Kit', 'Thermal Camera'],
    completedJobs: 2100
  },
  {
    id: '4',
    name: 'Vikram Singh',
    category: 'Mechanic',
    location: 'Whitefield, Bangalore',
    availability: 'Available',
    rating: 4.7,
    reviewsCount: 512,
    reviews: MOCK_REVIEWS,
    price: '₹800',
    avatar: 'images/mechanic.jpg',
    lat: 12.9698,
    lng: 77.7500,
    description: 'On-site car service expert for luxury and German vehicles.',
    longBio: 'Don\'t wait at service centers. I provide full-synthetic oil changes and computer diagnostics at your doorstep.',
    skills: ['Diagnostics', 'Engine Tuning', 'Brake Pad Replacement'],
    yearsExperience: 10,
    responseTime: '45 mins',
    verified: true,
    repeatCustomers: 180,
    certifications: ['Automotive Excellence', 'EV Hybrid Specialist'],
    equipment: ['OBD2 Scanner', 'Hydraulic Jack System', 'Impact Wrenches'],
    completedJobs: 1320
  },
  {
    id: '5',
    name: 'Ananya Rao',
    category: 'Wellness',
    location: 'Bandra West, Mumbai',
    availability: 'Offline',
    rating: 4.9,
    reviewsCount: 88,
    reviews: MOCK_REVIEWS,
    price: '₹1500',
    avatar: 'images/yoga.jpg',
    lat: 19.0596,
    lng: 72.8295,
    description: 'Holistic Yoga instructor and mindfulness coach.',
    longBio: 'Personalized Hatha and Ashtanga yoga sessions designed for the busy professional. Certified from Rishikesh.',
    skills: ['Pranayama', 'Weight Management', 'Stress Relief'],
    yearsExperience: 6,
    responseTime: '1 hour',
    verified: false,
    repeatCustomers: 42,
    certifications: ['Yoga Alliance RYT-500', 'Sound Healing Cert'],
    equipment: ['Natural Cork Mats', 'Aromatherapy Diffusers', 'Singing Bowls'],
    completedJobs: 450
  },
  {
    id: '6',
    name: 'Suresh Kumar',
    category: 'Cleaning',
    location: 'Juhu, Mumbai',
    availability: 'Available',
    rating: 4.6,
    reviewsCount: 742,
    reviews: MOCK_REVIEWS,
    price: '₹299',
    avatar: 'images/cleaner.jpg',
    lat: 19.1075,
    lng: 72.8263,
    description: 'Deep cleaning expert for homes, sofas, and mattresses.',
    longBio: 'Using industrial-grade vacuum cleaners and eco-friendly chemicals to ensure your home is 99% germ-free.',
    skills: ['Sofa Shampooing', 'Kitchen Deep Clean', 'Pest Control'],
    yearsExperience: 5,
    responseTime: '25 mins',
    verified: true,
    repeatCustomers: 310,
    certifications: ['Eco-Clean Certified', 'BICS Standard'],
    equipment: ['Steam Cleaner', 'HEPA Vacuum', 'Ozone Generator'],
    completedJobs: 2400
  },
  {
    id: '7',
    name: 'Karan Mehra',
    category: 'Home Maintenance',
    location: 'Powai, Mumbai',
    availability: 'Available',
    rating: 4.8,
    reviewsCount: 120,
    reviews: MOCK_REVIEWS,
    price: '₹400',
    avatar: 'images/maid.webp',
    lat: 19.1176,
    lng: 72.9060,
    description: 'Professional painter and wood polisher.',
    longBio: 'I offer Asian Paints certified textures and waterproofing solutions for walls that last for years.',
    skills: ['Waterproofing', 'Wall Textures', 'Wood Polishing'],
    yearsExperience: 11,
    responseTime: '40 mins',
    verified: true,
    repeatCustomers: 64,
    certifications: ['Asian Paints Certified', 'Furniture Finishing Pro'],
    equipment: ['Airless Sprayer', 'Dustless Sander', 'Moisture Meter'],
    completedJobs: 680
  },
  {
    id: '8',
    name: 'Rohit Patil',
    category: 'Plumbing',
    location: 'Borivali East, Mumbai',
    availability: 'Available',
    rating: 4.7,
    reviewsCount: 156,
    reviews: MOCK_REVIEWS,
    price: '₹450',
    avatar: 'images/plumber.webp',
    lat: 19.2307,
    lng: 72.8567,
    description: 'Expert in bathroom renovations and water heater installations.',
    longBio: 'Serving Borivali and nearby areas for 8 years. Specialized in modern bathroom fittings and emergency plumbing repairs.',
    skills: ['Bathroom Renovation', 'Water Heater Repair', 'Pipe Installation'],
    yearsExperience: 8,
    responseTime: '20 mins',
    verified: true,
    repeatCustomers: 89,
    certifications: ['Licensed Plumber', 'Safety Certified'],
    equipment: ['Pipe Cutter', 'Drain Snake', 'Pressure Tester'],
    completedJobs: 890
  },
  {
    id: '9',
    name: 'Neha Joshi',
    category: 'Beauty',
    location: 'Borivali East, Mumbai',
    availability: 'Busy',
    rating: 4.9,
    reviewsCount: 203,
    reviews: MOCK_REVIEWS,
    price: '₹1100',
    avatar: 'images/makeup.jpg',
    lat: 19.2285,
    lng: 72.8590,
    description: 'Professional makeup artist specializing in bridal and party makeup.',
    longBio: 'Trained beautician with expertise in all skin types. Provides premium home service with organic products.',
    skills: ['Bridal Makeup', 'Party Makeup', 'Skincare'],
    yearsExperience: 6,
    responseTime: '25 mins',
    verified: true,
    repeatCustomers: 145,
    certifications: ['Beauty Therapy Diploma', 'Makeup Artist Certified'],
    equipment: ['Professional Kit', 'Airbrush System', 'LED Mirror'],
    completedJobs: 650
  },
  {
    id: '10',
    name: 'Amit Sharma',
    category: 'Electrical',
    location: 'Kandivali West, Mumbai',
    availability: 'Available',
    rating: 4.6,
    reviewsCount: 178,
    reviews: MOCK_REVIEWS,
    price: '₹380',
    avatar: 'images/electrician.jpg',
    lat: 19.2095,
    lng: 72.8526,
    description: 'Licensed electrician for home and commercial electrical work.',
    longBio: 'Experienced in LED installations, electrical panel upgrades, and smart home automation systems.',
    skills: ['LED Installation', 'Panel Upgrade', 'Smart Home Setup'],
    yearsExperience: 12,
    responseTime: '30 mins',
    verified: true,
    repeatCustomers: 134,
    certifications: ['Licensed Electrician', 'Smart Home Specialist'],
    equipment: ['Digital Tester', 'Cable Puller', 'Voltage Detector'],
    completedJobs: 1250
  },
  {
    id: '11',
    name: 'Deepak Singh',
    category: 'Cleaning',
    location: 'Malad East, Mumbai',
    availability: 'Available',
    rating: 4.5,
    reviewsCount: 298,
    reviews: MOCK_REVIEWS,
    price: '₹320',
    avatar: 'images/cleaner.jpg',
    lat: 19.1868,
    lng: 72.8492,
    description: 'Professional deep cleaning and sanitization services.',
    longBio: 'Eco-friendly cleaning solutions for homes and offices. Specialized in post-construction cleaning.',
    skills: ['Deep Cleaning', 'Sanitization', 'Post-Construction Cleanup'],
    yearsExperience: 7,
    responseTime: '35 mins',
    verified: false,
    repeatCustomers: 187,
    certifications: ['Cleaning Professional', 'Safety Training'],
    equipment: ['Steam Cleaner', 'Vacuum System', 'Eco Products'],
    completedJobs: 1890
  }
];

export const CATEGORIES: string[] = [
  'Plumbing', 'Electrical', 'Tutoring', 'Mechanic', 'Home Maintenance', 'Gardening', 'Cleaning', 'Moving', 'Pet Care', 'Beauty', 'Wellness', 'Appliance Repair', 'AC Repair'
];

export const LOCATIONS: string[] = [
  'Koramangala', 'Indiranagar', 'HSR Layout', 'Whitefield', 'Bandra West', 'Juhu', 'Powai', 'Hauz Khas', 'Gurgaon', 'Borivali East', 'Kandivali West', 'Malad East'
];
